### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/pga#1]
# TODO

* [ ] - USB, including freezing relevant micropython-lib stuff
* [x] - Add some LittleFS files, dir2uf2, etc
* [ ] - License, MIT as always
* [ ] - More documentation
* [ ] - Retarget at a proper MicroPython release once PSRAM and RP2350 PRs are merged

**Comment by dyaa** [comment]
I'm curious to know why this repo isn't part of another repo related to pico and pimoroni's RP2350? 🤔

**Comment by Gadgetoid** [comment]
Which repo are you angling at?

I think the README here explains it? Let me know if anything needs clarifying.

PGA is intended to help people build their own boards, so it stands to reason that a fraction of those would want to customise the software and might have a different class of requirements, questions, requests or suggestions. This repository exists to facilitate that.

Also putting all the builds in one place just isn't sustainable, especially when it's built upon a teetering tower of unmerged changes to MicroPython. We have waaaay too many flavours of batteries included MicroPython at this point 😭
